from __future__ import annotations

from pydantic import BaseModel, Field
from typing import Literal, Optional, Any
from datetime import datetime, timezone
import uuid


GoalType = Literal["analysis", "prediction", "unsure"]


class Inputs(BaseModel):
    dataset_paths: list[str] = Field(default_factory=list)
    problem_statement: str
    audience: str
    goal_type: GoalType
    success_metric: str

    # Optional
    data_dictionary: Optional[str] = None  # free text or pasted dict
    target_column: Optional[str] = None  # user specified, optional


class Question(BaseModel):
    question: str
    why: str
    priority: Literal["high", "medium", "low"] = "medium"
    answer: Optional[str] = None  # User's answer to the question


class UserFeedback(BaseModel):
    """User corrections to pipeline decisions."""
    node: str  # Which node's decision this applies to
    decision_type: str  # e.g., "outliers_detected", "duplicates_detected", "pii_check"
    action: str  # "keep_rows", "ignore_flagging", "override"
    affected_indices: list[int] = Field(default_factory=list)  # Row indices to keep/ignore
    reason: Optional[str] = None  # User's explanation
    timestamp: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())


class Profile(BaseModel):
    rows: int
    cols: int
    columns: list[str]
    dtypes: dict[str, str]
    missing_pct: dict[str, float]
    n_unique: dict[str, int]
    sample_rows: list[dict[str, Any]] = Field(default_factory=list)
    numeric_stats: dict[str, dict[str, Any]] = Field(default_factory=dict)
    cardinality: dict[str, Any] = Field(default_factory=dict)
    date_ranges: dict[str, dict[str, Any]] = Field(default_factory=dict)


class Chart(BaseModel):
    title: str
    path: str
    kind: str  # histogram, correlation, bar, ...
    caption: str = ""


class Finding(BaseModel):
    statement: str
    evidence: str  # concrete numbers backing the statement
    confidence: float = 0.5
    caveat: str = ""


class EDAResult(BaseModel):
    charts: list[Chart] = Field(default_factory=list)
    correlations: list[dict[str, Any]] = Field(default_factory=list)
    target_relationships: list[dict[str, Any]] = Field(default_factory=list)
    findings: list[Finding] = Field(default_factory=list)


class Insights(BaseModel):
    headline: str
    narrative: str
    recommendations: list[str] = Field(default_factory=list)
    risks: list[str] = Field(default_factory=list)


class LineageSnapshot(BaseModel):
    rows: int
    cols: int
    columns: list[str]
    dtypes: dict[str, str]
    missing_pct: dict[str, float]
    n_unique: dict[str, int]
    sample_rows: list[dict[str, Any]] = Field(default_factory=list)
    numeric_stats: dict[str, dict[str, Any]] = Field(default_factory=dict)
    cardinality: dict[str, Any] = Field(default_factory=dict)
    date_ranges: dict[str, dict[str, Any]] = Field(default_factory=dict)


class LineageEntry(BaseModel):
    node: str
    timestamp: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    input: Optional[LineageSnapshot] = None
    transformations: list[dict[str, Any]] = Field(default_factory=list)
    output: Optional[LineageSnapshot] = None
    decisions: list[dict[str, Any]] = Field(default_factory=list)


class RunConfig(BaseModel):
    run_id: str = Field(default_factory=lambda: uuid.uuid4().hex[:8])
    created_at: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    pii_column_patterns: list[str] = Field(
        default_factory=lambda: ["email", "e-mail", "phone", "ssn", "social", "address", "name"]
    )


class RunState(BaseModel):
    config: RunConfig = Field(default_factory=RunConfig)
    inputs: Inputs

    # Generated by agents/tools
    user_questions: list[Question] = Field(default_factory=list)
    internal_questions: list[Question] = Field(default_factory=list)
    improved_problem_statement: Optional[str] = None
    profile: Optional[Profile] = None
    eda: Optional[EDAResult] = None
    insights: Optional[Insights] = None
    user_feedback: list[UserFeedback] = Field(default_factory=list)

    # Simple audit log (safe, concise)
    audit: list[dict[str, Any]] = Field(default_factory=list)
    lineage: list[LineageEntry] = Field(default_factory=list)

    stage: Literal["init", "intake_done", "profile_done", "eda_done", "insights_done", "failed"] = "init"
    errors: list[str] = Field(default_factory=list)
